package dev.basedpython.pycharm.project

import com.intellij.openapi.project.Project
import com.intellij.openapi.roots.impl.DirectoryIndexExcludePolicy
import com.intellij.openapi.vfs.VfsUtilCore

/**
 * Excludes `out/` directories at content-root level from IDE indexing.
 *
 * Without this, the `.py` files generated by `by build` pollute search results,
 * the "Go to Class" index, and Find Usages — all of which should operate on
 * the `.by` source files instead.
 *
 * The policy is evaluated per-project. It adds the URL for `<projectBase>/out/`
 * so transpiled `.py` files are treated as excluded even when the directory
 * doesn't exist yet (IntelliJ accepts future-URL exclusions).
 *
 * Registration in plugin.xml (Stream O integration):
 *
 *   <directoryIndexExcludePolicy
 *       implementation="dev.basedpython.pycharm.project.OutDirExcludePolicy"/>
 */
class OutDirExcludePolicy(private val project: Project) : DirectoryIndexExcludePolicy {

    /**
     * Returns the URL of `<project-base>/out` so it is treated as an excluded root.
     *
     * IntelliJ's [DirectoryIndexExcludePolicy] interface defines this as a default
     * method returning an empty array; we override it to add the `out/` dir.
     */
    override fun getExcludeUrlsForProject(): Array<String> {
        val basePath = project.basePath ?: return emptyArray()
        val outUrl = VfsUtilCore.pathToUrl("$basePath/out")
        return arrayOf(outUrl)
    }
}
