package dev.basedpython.pycharm.project

import com.intellij.openapi.project.Project
import com.intellij.openapi.roots.ProjectRootManager
import com.intellij.openapi.roots.impl.DirectoryIndexExcludePolicy
import com.intellij.openapi.vfs.VfsUtilCore
import dev.basedpython.pycharm.settings.BasedPythonSettings

/**
 * Excludes `out/` directories from IDE indexing — one per content root, so the
 * policy works for multi-root / multi-module workspaces (§185), not just the
 * primary project base.
 *
 * Without this, the `.py` files generated by `by build` pollute search results,
 * the "Go to Class" index, and Find Usages — all of which should operate on
 * the `.by` source files instead.
 *
 * IntelliJ accepts future-URL exclusions, so `<root>/out` is excluded even when
 * the directory does not exist yet.
 *
 * Opt-out: when [BasedPythonSettings.indexGeneratedPython] is enabled the user
 * wants a Python plugin to index the generated `.py`, so nothing is excluded.
 *
 * Registration in plugin.xml:
 *
 *   <directoryIndexExcludePolicy
 *       implementation="dev.basedpython.pycharm.project.OutDirExcludePolicy"/>
 */
class OutDirExcludePolicy(private val project: Project) : DirectoryIndexExcludePolicy {

    override fun getExcludeUrlsForProject(): Array<String> {
        // Opt-in reuse of Python tooling: when the user wants native Python code
        // intelligence on the generated `.py` files (requires a Python plugin),
        // stop excluding `out/` so the Python plugin indexes it.
        if (BasedPythonSettings.getInstance(project).indexGeneratedPython) {
            return emptyArray()
        }
        return outUrls(project)
    }

    companion object {
        /**
         * Compute the set of `<contentRoot>/out` URLs to exclude across every
         * content root in the project, plus the project base path as a fallback
         * (covers projects whose roots are not yet loaded). Deduplicated.
         */
        fun outUrls(project: Project): Array<String> {
            val urls = linkedSetOf<String>()

            // Every content root of every module (multi-root / multi-module aware).
            ProjectRootManager.getInstance(project).contentRootUrls.forEach { rootUrl ->
                urls += joinUrl(rootUrl, "out")
            }

            // Fallback: project base, in case roots are not registered yet.
            project.basePath?.let { base ->
                urls += VfsUtilCore.pathToUrl("$base/out")
            }

            return urls.toTypedArray()
        }

        /** Append [child] to a VFS [parentUrl], normalising the separator. */
        private fun joinUrl(parentUrl: String, child: String): String =
            parentUrl.trimEnd('/') + "/" + child
    }
}
